name: Tests

on:
  - push
  - pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure and build
        run: |
          mkdir -p build
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target huffman testHuffman

      - name: Generate output files
        working-directory: tests
        run: |
          ../build/huffman --compress test1.txt test1compressed.huff
          ../build/huffman --decompress test1compressed.huff test1restored.txt
          ../build/huffman --compress test2.txt test2compressed.huff
          ../build/huffman --decompress test2compressed.huff test2restored.txt
          ../build/huffman --compress test3.txt test3compressed.huff
          ../build/huffman --decompress test3compressed.huff test3restored.txt
          ../build/huffman --compress test4russian.txt test4compressed.huff
          ../build/huffman --decompress test4compressed.huff test4restored.txt
          ../build/huffman --compress test5.txt test5compressed.huff
          ../build/huffman --decompress test5compressed.huff test5restored.txt

      - name: Run tests
        working-directory: build
        run: ./testHuffman

